" # Global settings
filetype plugin indent on
syntax on

:scriptencoding utf-8
let &showbreak = '↪ '
set clipboard=unnamed
set completeopt+=longest
set completeopt-=preview
set expandtab
set hidden
set lbr
set mouse=a
set nomodeline
set noswapfile
set number
set path=**
set shell=/bin/bash " required by gitgutter plugin
set updatetime=100  " ensures gitgutter updates every 100ms
set shiftround
set shiftwidth=2
set splitbelow
set splitright
set tabstop=2
set termguicolors
set undodir=~/tmp/vim/undo
set undofile
set wildignorecase

" # Plugin configuration
let g:EditorConfig_exclude_patterns = ['.git/COMMIT_EDITMSG']
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#vimagit#enabled = 1
let g:ale_elm_make_use_global=1
let g:ale_linters = { 'haskell': ['hlint', 'hdevtools'] }
let g:ale_sign_error = '✗'
let g:ale_sign_warning = '!'
let g:deoplete#enable_at_startup = 1
let g:elm_format_autosave = 0
let g:elm_make_show_warnings = 1
let g:elm_setup_keybindings = 0
let g:fzf_layout = { 'window': 'enew' }
let g:haskell_indent_disable=1 "Automatic indenting and hindent don't agree
let g:localvimrc_persistent=2 "See plugin: embear/vim-localvimrc
let g:neoterm_autoinsert = 1
let g:neoterm_autoscroll = 1
let g:neoterm_default_mod = 'tab'
let g:netrw_liststyle=1
let g:polyglot_disabled = ['haskell', 'markdown']
let g:startify_change_to_vcs_root = 1
let g:startify_session_delete_buffers = 1
let g:test#strategy = 'neoterm'
let $FZF_DEFAULT_OPTS .= ' --no-height' " fixes fzf in nvim terminals

if !isdirectory(expand(&undodir))
   call mkdir(expand(&undodir), 'p')
endif

let g:neoformat_nix_nixfmt = {
  \ 'exe': 'nixfmt',
  \ 'args': [],
  \ 'stdin': 1,
  \ }
let g:neoformat_enabled_nix = ['nixfmt']

" # Mappings
let g:mapleader=' '
let g:maplocalleader='\'

" Perform fuzzy file searching
nnoremap <C-P> :Files<cr>
nnoremap <C-B> :Buffers<CR>

" Terminal mappings
tnoremap <C-[> <C-\><C-n>
tnoremap <C-O> <C-\><C-n>`N

" # Autocmds
augroup customCommands
  autocmd!
  nmap <silent> <localleader>e <Plug>(ale_detail)
  autocmd BufWritePre * Neoformat
  " Remove trailing whitespace upon saveing.
  autocmd BufWritePre * :%s/\s\+$//e

  " don't show fzf statusline
  autocmd  FileType fzf set laststatus=0 noshowmode noruler
    \| autocmd BufLeave <buffer> set laststatus=2 showmode ruler
augroup END

command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always '.shellescape(<q-args>).'| tr -d "\017"', 1,
  \   { 'options': '--bind ctrl-a:select-all,ctrl-d:deselect-all' },
  \   <bang>0)

command! -bang -nargs=? -complete=dir Files
  \ call fzf#vim#files(<q-args>, { 'options': '--bind ctrl-a:select-all,ctrl-d:deselect-all' }, <bang>0)

" Personal settings
let g:neoterm_shell = 'fish'
set colorcolumn=81
let g:neoformat_enabled_ruby = []
let g:neoformat_enabled_rust = []
let g:neoformat_enabled_sql = []
let g:neoformat_enabled_yaml = []
let g:neoformat_enabled_json = []
set spell spelllang=en_us

" Colors
colorscheme candid
set background=dark
let g:lightline = { 'colorscheme': 'candid' }
